"""Export helpers: batch PNG export and optional PDF report."""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

import pandas as pd

import logging
logger = logging.getLogger(__name__)


def export_all_plots(
    df: pd.DataFrame,
    output_dir: str | Path,
    fps: float = 25.0,
    street_start_m: float = 2.0,
    street_end_m: float = 6.0,
    group_stats: dict | None = None,
) -> list[Path]:
    """Export all available plots to PNG files in *output_dir*.

    Args:
        df: Trajectory DataFrame.
        output_dir: Directory in which plots are saved.
        fps: Frames per second.
        street_start_m: Street crossing start (m).
        street_end_m: Street crossing end (m).
        group_stats: Optional dict from
            :func:`pipeline.group_analysis.compute_group_statistics`.

    Returns:
        List of :class:`pathlib.Path` objects for all created PNG files.
    """
    from visualization.plot_trajectories import plot_trajectories
    from visualization.plot_heatmap import plot_heatmap
    from visualization.plot_behavior import plot_behavior_timeline
    from visualization.plot_swarm import plot_swarm_metrics
    from visualization.plot_groups import plot_group_statistics
    from utils.paths import get_timestamp

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    ts = get_timestamp()
    saved: list[Path] = []

    def _try(fn, *args, **kwargs):
        try:
            p = fn(*args, **kwargs)
            if p is not None:
                saved.append(p)
        except Exception as exc:
            logger.error("Plot export failed (%s): %s", fn.__name__, exc)

    _try(plot_trajectories, df, street_start_m, street_end_m,
         output_path=output_dir / f"trajectories_{ts}.png")
    _try(plot_heatmap, df, output_path=output_dir / f"heatmap_{ts}.png")
    _try(plot_behavior_timeline, df, fps, output_path=output_dir / f"behavior_{ts}.png")
    _try(plot_swarm_metrics, df, fps, output_path=output_dir / f"swarm_{ts}.png")

    if group_stats:
        _try(plot_group_statistics, group_stats, output_path=output_dir / f"groups_{ts}.png")

    logger.info("Exported %d plots to '%s'", len(saved), output_dir)
    return saved


def export_pdf_report(
    plot_paths: Sequence[str | Path],
    output_path: str | Path,
    title: str = "Pedestrian Analysis Report",
) -> Path:
    """Combine exported plot PNGs into a simple PDF report.

    Args:
        plot_paths: List of PNG file paths to include.
        output_path: Destination PDF file path.
        title: Report title shown on the first page.

    Returns:
        :class:`pathlib.Path` to the created PDF.

    Raises:
        ImportError: When *fpdf2* is not installed.
        ValueError: When *output_path* is a directory.
    """
    try:
        from fpdf import FPDF
    except ImportError as exc:
        raise ImportError("fpdf2 is required for PDF export. Install it with: pip install fpdf2") from exc

    from utils.validation import assert_is_not_directory

    output_path = Path(output_path)
    assert_is_not_directory(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=10)

    # Title page
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 20, title, ln=True, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, f"Generated by Pedestrian Crossing Trajectory Analysis", ln=True, align="C")

    for p in plot_paths:
        p = Path(p)
        if not p.is_file():
            logger.warning("Skipping missing plot file: '%s'", p)
            continue
        pdf.add_page()
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, p.stem, ln=True)
        pdf.image(str(p), x=10, y=20, w=190)

    pdf.output(str(output_path))
    logger.info("Saved PDF report to '%s'", output_path)
    return output_path
